### ISSUE TITLE
Remove plagiarized content

### ISSUE THREAD

**Issue by chantastic** [vasanthk/react-bits#21]
Many of the items are plagiarised from reactpatterns.com, which is not licensed.

The content on reactpatterns.com is *not* licensed. Making this content a copyright violation.

Please let me know that you received this issue and we'll work toward an immicable solution.

As a trainer I take these violations very seriously.

**Comment by vasanthk** [comment]
Sorry, I wasn't aware of the license. It's a great resource and thank you for putting it up. I have added references in the bottom of the Readme. Happy to do what it takes to remove it or attribution. Just tried to share my learnings.

**Comment by chantastic** [comment]
Thanks for the quick response.

I'm going to do more research in the morning. Part of the issue is that it's been forked and violations exist elsewhere. Additionally, the violations live on in the commit history.

Thanks for your willingness to resolve the issue.

**Comment by vasanthk** [comment]
Thanks, just felt that using them as is with reference was better than mildly updating examples.
FWIW, I can remove them completely and add in my examples if that helps. Whatever works.

**Comment by nuragic** [comment]
Hi guys,

I've just run into this repo, looking forward to make a small contribution, then I saw this issue that caught my attention.

Both this repo and react patterns are great resources IMO, and I guess that we're all thankful about the fact that all this knowledge has been _made public and free for personal use_. 

However, let me ask a question: what's the deal of putting your content on GitHub, in a **public** repo, if in reality you don't want people to share/modify it? With having your repo here, **public**, [you're de-facto accepting GitHub terms and conditions and at least you allow people to fork and make pull requests](https://help.github.com/articles/licensing-a-repository/).

That being said, I'm not going to make into question your `NO LICENSE` _(i.e. copyright©)_ decision, neither that's **your** content and that people **must** ask you before re-distributing, etc. I just want to finally ask you: why don't you explicitly add a _disclaimer_ section in your README, whatever, to make sure nobody would ever end up in this situation again?

I guess there's also people like me that don't want to contribute to copyrighted material, so it would be definitely better if you make it transparent and clear in the first place.

Thanks in advance!

**Comment by vasanthk** [comment]
@nuragic I personally wasn't aware about the "NO LICENSE" catch means copyrighted before this issue. However, I can understand from the perspective of a React trainer why it might be a little uncomfortable. So, sorry about that. I had replied earlier with suggestions but haven't heard back since.

I have various other projects I have contributed to in OSS/personal github and I just think of it as a way of giving back to the community from which I learnt so much. All of the projects in my Github are free to contribute/do [whatever you want to](http://www.wtfpl.net/about/). 

In this particular repo, especially with things like patterns/examples it is hard to draw boundaries around ownership I feel. I thank folks for all the wonderful resources that helped me with this. There also includes a bunch of patterns which I shared during my tech talks/implementations I came up with at work. I felt this was a good medium to consolidate and put it out there for rest of the world to look into and share new ideas as well. I have referenced various links in each of the files and also have a section linked for related reading. I have added a MIT LICENSE for this repo and will do the same to all my other repos as well to avoid confusion.

I like to drive projects as a community rather than in silo. So, happy to accept contributions/suggestions/better ways to do this 😊

**Comment by nuragic** [comment]
@vasanthk Thanks so much for your response! Really happy you finally opted to add a license... 👏  🎩 

BTW, to be honest, I would have used a [Creative Commons Attribution Share Alike 4.0](https://choosealicense.com/licenses/cc-by-sa-4.0/) license in this case, rather than [MIT](https://choosealicense.com/licenses/mit/) (which is specifically for `software`). I'm also a musician so I've used CC licenses for more than 10 years. 😄   I also take this kind of stuff seriously, but sometimes we can have different point of views regarding copyright, etc. which is totally normal.

_P.S. Looking forward to improve some parts -- specifically https://github.com/vasanthk/react-bits/blob/master/anti-patterns/06.using-indexes-as-key.md. I think that simply state that's an antipattern can be confusing for beginners. [React Official Docs are quite clear on this part](https://facebook.github.io/react/docs/lists-and-keys.html#keys-must-only-be-unique-among-siblings), so I'd simply update that `bit`._ 😉 

Thanks again! 🍻

**Comment by vasanthk** [comment]
@nuragic Thanks. I am ok with whichever license is most permissible for others. Updated it to CC 4.0 👍

**Comment by chantastic** [comment]
@nuragic had the content been released under MIT or CC, it would still require attribution, which the project owner omitted and removed links back to original content.

**Comment by chantastic** [comment]
Reopened as #66

**Comment by nuragic** [comment]
@chantastic Hi Michael,

Of course, attribution is the deal... as far as I understood, @vasanthk is keen to put the attribution notice in whatever place you prefer, correct me if I'm wrong... as he stated earlier:

> I have added references in the bottom of the Readme. Happy to do what it takes to remove it or add attribution

The only problem for me right now is that I actually don't understand your will, really: could you clarify if in reality:

1) you're ok about using some content from react patterns, with your permission, putting attribution, etc.
2) you would rather want to see this so-called _plagiarized content_ removed, as you state on this issue title

Finally, I'd also love if you would think about re-considering your `no license` choice... You know, this is GitHub... it supposed to work like this... nobody is here to "steal" or "plagiarize", I guess... 

Anyway, I'm not here to judge your license choice, but please, if you still want to keep it like so, just add a copyright notice or something like that in your README, just to avoid this kind of issue in the future and make clear what are your expectation about sharing / re-using your content.

Thanks for your time
